2025-10-29 01:15:17,481 -  nornir.core -     INFO -        run() - Running task 'send_command' with args {'command': 'show version'} on 2 hosts
2025-10-29 01:15:17,487 - nornir.core.task -    ERROR -      start() - Host 'sbx-nxos-mgmt': task 'send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\task.py", line 98, in start
    r = self.task(self, **self.params)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir_scrapli\tasks\core\send_command.py", line 37, in send_command
    scrapli_conn = task.host.get_connection("scrapli", task.nornir.config)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\inventory.py", line 476, in get_connection
    self.open_connection(
    ~~~~~~~~~~~~~~~~~~~~^
        connection=connection,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        extras=conn.extras,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\inventory.py", line 528, in open_connection
    conn_obj.open(
    ~~~~~~~~~~~~~^
        hostname=hostname,
        ^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        configuration=configuration,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir_scrapli\connection.py", line 99, in open
    connection = Scrapli(**parameters, platform=final_platform)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\factory.py", line 517, in __new__
    final_conn = final_driver(**final_kwargs)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\core\cisco_nxos\sync_driver.py", line 135, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        host=host,
        ^^^^^^^^^^
    ...<31 lines>...
        genie_platform=genie_platform,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\network\sync_driver.py", line 53, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        host=host,
        ^^^^^^^^^^
    ...<25 lines>...
        logging_uid=logging_uid,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\generic\sync_driver.py", line 69, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        host=host,
        ^^^^^^^^^^
    ...<26 lines>...
        logging_uid=logging_uid,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\base\sync_driver.py", line 16, in __init__
    super().__init__(**kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\base\base_driver.py", line 209, in __init__
    self.transport = transport_class(
                     ~~~~~~~~~~~~~~~^
        base_transport_args=self._base_transport_args,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        plugin_transport_args=self._plugin_transport_args,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\transport\plugins\system\transport.py", line 64, in __init__
    raise ScrapliUnsupportedPlatform("system transport is not supported on windows devices")
scrapli.exceptions.ScrapliUnsupportedPlatform: system transport is not supported on windows devices

2025-10-29 01:15:17,488 - nornir.core.task -    ERROR -      start() - Host 'sandbox-iosxr-1': task 'send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\task.py", line 98, in start
    r = self.task(self, **self.params)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir_scrapli\tasks\core\send_command.py", line 37, in send_command
    scrapli_conn = task.host.get_connection("scrapli", task.nornir.config)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\inventory.py", line 476, in get_connection
    self.open_connection(
    ~~~~~~~~~~~~~~~~~~~~^
        connection=connection,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        extras=conn.extras,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\inventory.py", line 528, in open_connection
    conn_obj.open(
    ~~~~~~~~~~~~~^
        hostname=hostname,
        ^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        configuration=configuration,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir_scrapli\connection.py", line 99, in open
    connection = Scrapli(**parameters, platform=final_platform)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\factory.py", line 517, in __new__
    final_conn = final_driver(**final_kwargs)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\core\cisco_iosxr\sync_driver.py", line 134, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        host=host,
        ^^^^^^^^^^
    ...<31 lines>...
        genie_platform=genie_platform,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\network\sync_driver.py", line 53, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        host=host,
        ^^^^^^^^^^
    ...<25 lines>...
        logging_uid=logging_uid,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\generic\sync_driver.py", line 69, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        host=host,
        ^^^^^^^^^^
    ...<26 lines>...
        logging_uid=logging_uid,
        ^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\base\sync_driver.py", line 16, in __init__
    super().__init__(**kwargs)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\base\base_driver.py", line 209, in __init__
    self.transport = transport_class(
                     ~~~~~~~~~~~~~~~^
        base_transport_args=self._base_transport_args,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        plugin_transport_args=self._plugin_transport_args,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\transport\plugins\system\transport.py", line 64, in __init__
    raise ScrapliUnsupportedPlatform("system transport is not supported on windows devices")
scrapli.exceptions.ScrapliUnsupportedPlatform: system transport is not supported on windows devices

2025-10-29 01:17:14,366 -  nornir.core -     INFO -        run() - Running task 'send_command' with args {'command': 'show version'} on 2 hosts
2025-10-29 01:17:15,724 - nornir.core.task -    ERROR -      start() - Host 'sandbox-iosxr-1': task 'send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\task.py", line 98, in start
    r = self.task(self, **self.params)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir_scrapli\tasks\core\send_command.py", line 37, in send_command
    scrapli_conn = task.host.get_connection("scrapli", task.nornir.config)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\inventory.py", line 476, in get_connection
    self.open_connection(
    ~~~~~~~~~~~~~~~~~~~~^
        connection=connection,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        extras=conn.extras,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\inventory.py", line 528, in open_connection
    conn_obj.open(
    ~~~~~~~~~~~~~^
        hostname=hostname,
        ^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        configuration=configuration,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir_scrapli\connection.py", line 106, in open
    connection.open()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\base\sync_driver.py", line 102, in open
    self.transport.open()
    ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\transport\plugins\paramiko\transport.py", line 90, in open
    self._verify_key()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\transport\plugins\paramiko\transport.py", line 126, in _verify_key
    raise ScrapliAuthenticationFailed(
        f"{self._base_transport_args.host} not in known_hosts!"
    )
scrapli.exceptions.ScrapliAuthenticationFailed: sandbox-iosxr-1.cisco.com not in known_hosts!

2025-10-29 01:17:15,840 - nornir.core.task -    ERROR -      start() - Host 'sbx-nxos-mgmt': task 'send_command' failed with traceback:
Traceback (most recent call last):
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\task.py", line 98, in start
    r = self.task(self, **self.params)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir_scrapli\tasks\core\send_command.py", line 37, in send_command
    scrapli_conn = task.host.get_connection("scrapli", task.nornir.config)
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\inventory.py", line 476, in get_connection
    self.open_connection(
    ~~~~~~~~~~~~~~~~~~~~^
        connection=connection,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
        extras=conn.extras,
        ^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir\core\inventory.py", line 528, in open_connection
    conn_obj.open(
    ~~~~~~~~~~~~~^
        hostname=hostname,
        ^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        configuration=configuration,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\nornir_scrapli\connection.py", line 106, in open
    connection.open()
    ~~~~~~~~~~~~~~~^^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\driver\base\sync_driver.py", line 102, in open
    self.transport.open()
    ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\transport\plugins\paramiko\transport.py", line 90, in open
    self._verify_key()
    ~~~~~~~~~~~~~~~~^^
  File "C:\Users\formanesf\AppData\Local\Programs\Python\Python313\Lib\site-packages\scrapli\transport\plugins\paramiko\transport.py", line 126, in _verify_key
    raise ScrapliAuthenticationFailed(
        f"{self._base_transport_args.host} not in known_hosts!"
    )
scrapli.exceptions.ScrapliAuthenticationFailed: sbx-nxos-mgmt.cisco.com not in known_hosts!

2025-10-29 01:18:12,683 -  nornir.core -     INFO -        run() - Running task 'send_command' with args {'command': 'show version'} on 2 hosts
